MusicApp/Models/tb_Cancion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cancion
    {
        public tb_Cancion()
        {
            this.tb_Comentarios = new HashSet<tb_Comentarios>();
            this.tb_DisLikeMusic = new HashSet<tb_DisLikeMusic>();
            this.tb_Playlist = new HashSet<tb_Playlist>();
        }
    
        public int ID_CANCION { get; set; }
        public int ID_ARTISTA { get; set; }
        public int ID_ALBUM { get; set; }
        public string Nombre_Cancion { get; set; }
        public Nullable<decimal> Numero_Cancion { get; set; }
        public string Ruta_Audio { get; set; }
        public int Duracion_Cancion { get; set; }
    
        public virtual tb_Album tb_Album { get; set; }
        public virtual tb_Artista tb_Artista { get; set; }
        public virtual ICollection<tb_Comentarios> tb_Comentarios { get; set; }
        public virtual ICollection<tb_DisLikeMusic> tb_DisLikeMusic { get; set; }
        public virtual ICollection<tb_Playlist> tb_Playlist { get; set; }
    }
}

MusicApp/Controllers/tb_CancionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicApp.Models;

namespace MusicApp.Controllers
{
    public class tb_CancionController : Controller
    {
        private BD_LOSS_SOUNDS2Entities db = new BD_LOSS_SOUNDS2Entities();

        // GET: tb_Cancion
        public ActionResult Index()
        {
            var tb_Cancion = db.tb_Cancion.Include(t => t.tb_Album).Include(t => t.tb_Artista);
            return View(tb_Cancion.ToList());
        }

        // GET: tb_Cancion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Cancion tb_Cancion = db.tb_Cancion.Find(id);
            if (tb_Cancion == null)
            {
                return HttpNotFound();
            }
            return View(tb_Cancion);
        }

        // GET: tb_Cancion/Create
        public ActionResult Create()
        {
            ViewBag.ID_ALBUM = new SelectList(db.tb_Album, "ID_ALBUM", "Nombre_album");
            ViewBag.ID_ARTISTA = new SelectList(db.tb_Artista, "ID_ARTISTA", "Nombre_Artista");
            return View();
        }

        // POST: tb_Cancion/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_CANCION,ID_ARTISTA,ID_ALBUM,Nombre_Cancion,Numero_Cancion,Ruta_Audio,PortadaFile")] tb_Cancion tb_Cancion)
        {
            if (ModelState.IsValid)
            {
                if (tb_Cancion.PortadaFile != null)
                {
                    byte[] imageData;
                    using (var binaryReader = new BinaryReader(tb_Cancion.PortadaFile.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(tb_Cancion.PortadaFile.ContentLength);
                    }
                    tb_Cancion.Portada = imageData;
                    // Guardar 'imageData' en la base de datos y luego redirigir a otra vista.
                    db.tb_Cancion.Add(tb_Cancion);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
               
            }
        

            ViewBag.ID_ALBUM = new SelectList(db.tb_Album, "ID_ALBUM", "Nombre_album", tb_Cancion.ID_ALBUM);
            ViewBag.ID_ARTISTA = new SelectList(db.tb_Artista, "ID_ARTISTA", "Nombre_Artista", tb_Cancion.ID_ARTISTA);
            return View(tb_Cancion);
        }


        // GET: tb_Cancion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Cancion tb_Cancion = db.tb_Cancion.Find(id);
            if (tb_Cancion == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_ALBUM = new SelectList(db.tb_Album, "ID_ALBUM", "Nombre_album", tb_Cancion.ID_ALBUM);
            ViewBag.ID_ARTISTA = new SelectList(db.tb_Artista, "ID_ARTISTA", "Nombre_Artista", tb_Cancion.ID_ARTISTA);
            return View(tb_Cancion);
        }

        // POST: tb_Cancion/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_CANCION,ID_ARTISTA,ID_ALBUM,Nombre_Cancion,Numero_Cancion,Ruta_Audio,Portada")] tb_Cancion tb_Cancion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_Cancion).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_ALBUM = new SelectList(db.tb_Album, "ID_ALBUM", "Nombre_album", tb_Cancion.ID_ALBUM);
            ViewBag.ID_ARTISTA = new SelectList(db.tb_Artista, "ID_ARTISTA", "Nombre_Artista", tb_Cancion.ID_ARTISTA);
            return View(tb_Cancion);
        }

        // GET: tb_Cancion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Cancion tb_Cancion = db.tb_Cancion.Find(id);
            if (tb_Cancion == null)
            {
                return HttpNotFound();
            }
            return View(tb_Cancion);
        }

        // POST: tb_Cancion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_Cancion tb_Cancion = db.tb_Cancion.Find(id);
            db.tb_Cancion.Remove(tb_Cancion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MusicApp/Views/tb_Cancion/Create.cshtml
@model MusicApp.Models.tb_Cancion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "tb_Cancion", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tb_Cancion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_ARTISTA, "ID_ARTISTA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_ARTISTA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_ARTISTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ALBUM, "ID_ALBUM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_ALBUM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_ALBUM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Cancion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Cancion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Cancion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero_Cancion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero_Cancion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero_Cancion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ruta_Audio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruta_Audio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruta_Audio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PortadaFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Portada, new { htmlAttributes = new { @class = "form-control" } })*@
                @*<img src="@Url.Action("GetImage", "Image", null)" alt="Imagen" />*@
                @*<input type="file" name="PortadaFile" id="file" />*@
                @Html.TextBoxFor(model => model.PortadaFile, new { type = "file", @class = "form-control" })


                @Html.ValidationMessageFor(model => model.PortadaFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MusicApp/Views/tb_Cancion/Delete.cshtml
@model MusicApp.Models.tb_Cancion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_Cancion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_Cancion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Cancion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero_Cancion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero_Cancion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ruta_Audio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruta_Audio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_Album.Nombre_album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_Album.Nombre_album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_Artista.Nombre_Artista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_Artista.Nombre_Artista)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicApp/Views/tb_Cancion/Details.cshtml
@model MusicApp.Models.tb_Cancion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tb_Cancion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_Cancion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Cancion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero_Cancion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero_Cancion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ruta_Audio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruta_Audio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Portada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Portada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_Album.Nombre_album)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_Album.Nombre_album)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_Artista.Nombre_Artista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_Artista.Nombre_Artista)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_CANCION }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MusicApp/Views/tb_Cancion/Edit.cshtml
@model MusicApp.Models.tb_Cancion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tb_Cancion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_CANCION)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ARTISTA, "ID_ARTISTA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_ARTISTA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_ARTISTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ALBUM, "ID_ALBUM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_ALBUM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_ALBUM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Cancion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Cancion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Cancion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero_Cancion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero_Cancion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero_Cancion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ruta_Audio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruta_Audio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruta_Audio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Portada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Portada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Portada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MusicApp/Views/tb_Cancion/Index.cshtml
@model IEnumerable<MusicApp.Models.tb_Cancion>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre_Cancion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero_Cancion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ruta_Audio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Portada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tb_Album.Nombre_album)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tb_Artista.Nombre_Artista)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre_Cancion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Numero_Cancion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ruta_Audio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Portada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tb_Album.Nombre_album)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tb_Artista.Nombre_Artista)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_CANCION }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_CANCION }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_CANCION })
        </td>
    </tr>
}

</table>